- integration testing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,24 +9,79 @@ on:
 jobs:
   flutter-tests:
     runs-on: macos-latest
-#    strategy:
-#      fail-fast: false
-#      matrix:
-#        flutter_version: [ dev, beta, stable ]
-#        os: [ ubuntu-latest, macos-latest ]
+    strategy:
+      matrix:
+        api-level: [31]
     steps:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Setup Java
-        uses: actions/setup-java@v1
+      - name: Setup Java 11
+        uses: actions/setup-java@v3
         with:
-          java-version: '12.x'
+          distribution: 'zulu'
+          java-version: 11
+
+#      - name: Setup Java
+#        uses: actions/setup-java@v1
+#        with:
+#          java-version: '12.x'
 
       - name: Setup Flutter 3.22.3
         uses: subosito/flutter-action@v1
         with:
           flutter-version: '3.22.3'
 
-      - run: flutter pub get
-      - run: flutter test integration_test/tests/create_tests.dart
+      - name: Gradle cache
+        uses: gradle/gradle-build-action@v2
+
+      - name: Install Maestro
+        run: curl -Ls "https://raw.githubusercontent.com/GuillermoDLCO/maestro/main/scripts/install.sh" | bash
+
+      - name: AVD cache
+        uses: actions/cache@v3
+        id: avd-cache
+        with:
+          path: |
+            ~/.android/avd/*
+            ~/.android/adb*
+          key: avd-${{ matrix.api-level }}
+
+      - name: Run setup script
+        run: ./setup_flutter_as_app.sh
+
+      - name: Create AVD and generate snapshot for caching
+        if: steps.avd-cache.outputs.cache-hit != 'true'
+        uses: reactivecircus/android-emulator-runner@v2
+        with:
+          api-level: ${{ matrix.api-level }}
+          target: android-tv
+          profile: tv_1080p
+          arch: x86
+          force-avd-creation: false
+          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+          disable-animations: false
+          avd-name: macos-ci-avd
+          script: echo "Generated AVD snapshot for caching."
+
+      - name: Run integration tests
+        uses: reactivecircus/android-emulator-runner@v2
+        with:
+          api-level: ${{ matrix.api-level }}
+          target: android-tv
+          arch: x86
+          profile: tv_1080p
+          force-avd-creation: false
+          avd-name: macos-ci-avd
+          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+          disable-animations: true
+          script: |
+            adb shell pm list packages | grep 'com.android.app.example' && adb uninstall com.android.app.example || echo "Application not found"
+            flutter build apk --debug --target-platform=android-x86
+            flutter install --debug
+            export MAESTRO_DRIVER_STARTUP_TIMEOUT=60000
+            ~/.maestro/bin/maestro test ./integration_test/run-test.yml
+            
+
+#      - run: flutter pub get
+#      - run: flutter test integration_test/tests/create_tests.dart
